language: rust
cache: cargo
rust:
- stable
- beta
- nightly
script:
- cargo test
- cargo test --no-default-features
matrix:
  allow_failures:
  - rust: nightly
deploy:
  provider: cargo
  on:
    repo: rust-transit/gtfs-structure
    branch: master
  token:
    secure: "ueRv1WwTsZ/mkKzYSrddGIM/XOqegGVvM6ZmDePcbObJbL5tcQp6UzVHGc9swgVOZXhVsxu+446OApgq6dPjhFZeugzvArnkrVBnc2pc8vW1IYMoVows3MBfedjt6sEu3ntF1COMbZ53nwtESxbgIs8u/3Pks3OZx2NEsPo9NLCE8Yfz0+NwgwlTv/fnAX4vFpqznAm4yFu6ZHkJYc0nQw+TYqs1LaTL4sJsbDsK4xQnoXfhvqfEzXc//TNPPfPiHBnJQr8TaBOk5fbm05UV/osej77bkQSVdbltXD8Gx4Pzr27Yp4NqQXv0IHzivDL20IALlCZRYwAwyUk3Nu//ar8CzwTdBcnBHkCtJFz2c0h1O/wKFQgLNIYf35L9vSxpqt6Pb2P7mstaG46j9RDICjFavACfqVnPxZDDj0uOaN/XZ2DWWxOrZSwrpxjvWYQbHpXJM5JYZqYfg8H+8zYRtBu40NmzBGkHKgRBIJXmaud6yt/nToB1YzpIyM2nj9ZFY5P4ub0LOFDro65f+JooEqw28bPc+tSTdi6x0fs4cGZXVpm8AcF7ZojjGvk8at3kC1HwxPmMDpSmMQiNl6omIaof5b9ZrqYlaEmPsdQgkpfo73LOMXVcr72A+eBcLEGkYk9heukd70Pk72flFr2xAREV01gijY9it14TD6Bap58="
