[package]
description = "Read GTFS (public transit timetables) files"
name = "gtfs-structures"
version = "0.5.2"
authors = ["Tristram Gräbener <tristramg@gmail.com>"]
repository = "https://github.com/Tristramg/gtfs-structure"
license = "MIT"

[features]
default = ["read-url"]
read-url = ["reqwest"]

[dependencies]
csv = "1.0.0-beta.5"
derivative = "1.0.0"
serde = "1.0"
serde_derive = "1.0"
chrono = "0.4"
itertools = "0.7.2"
failure = "0.1.1"
failure_derive = "0.1.1"
zip = "0.3.1"

reqwest = { version = "0.8.5", optional = true }
